### PR TITLE
PWZGUI Interface Build

### PR DESCRIPTION
**Pull request by SpinnerX**
Here is the PWZGUI interface code.

### CODE REVIEW

**Comment by MattHazard** [comment]
The commit is good and we can hold the pull request until the next commit when the main function is able to take in and change the needed variables.

**Review by MattHazard — CHANGES_REQUESTED** [review]
This file shouldn't be changed by you (except for testing purposes). You don't have to git add this file to your commits.

**Comment by mrparmesan01** [comment]
Just undid the commit changes, to the requested file ID, that you had requested me to undo.

**Comment by MattHazard** [comment]
You have to be very careful about the folders/files you git add to your commits. You have your .vscode directory in your commit which needs to be removed.

**Review by MattHazard — APPROVED** [review]

**Comment by MattHazard** [comment]
Also it looks like the commit was not actually reverted because the code is still changed in PWZ.java

**Review by MattHazard — APPROVED** [review]
It will need some variable name changes but good enough to merge into the main branch for now.

**Comment by mrparmesan01** [comment]
Okay. I will keep that in mind, the next time I make commit changes. Just to add in the changes in the file I'm working on, rather than the main file. Thank You!

**Pull request merged**
